### ISSUE TITLE
Error when deployed on cloud provider

### ISSUE THREAD

**Issue by wksantiago** [trinsic-id/issuer-reference-app#19]
When I run the app on my local host it works fine but when deployed on cloud provider I get the following error.

Error at at /app/routes/api.js:24:20
```(node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'connectionId' of undefined```

```Error
2020-09-29T00:54:56.361796+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'connectionId' of undefined
2020-09-29T00:54:56.361798+00:00 app[web.1]: at /app/routes/api.js:24:20
2020-09-29T00:54:56.361798+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-29T00:54:56.361860+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)```

**Comment by michaeldboyd** [comment]
Are you able to get an error message or stack trace on the unhandled error that is returned from the API? It looks like the real failure is happening on the `client.createInvitation({})` call on [line 14](https://github.com/trinsic-id/issuer-reference-app/blob/df193895d7aace7ac21c14e8eafbfeacfa4e99a6/routes/api.js#L14). Have you made sure your environment variables are loading correctly? That may be a problem when migrating to a cloud provider.

**Comment by wksantiago** [comment]
Thanks for you pointer I realized that it had the .env file in .gitignore so it (the variables) was never sent to the cloud in this case it was Heroku(AWS) infrastructure.

So I just ignored .env ignored in the .gitignore file
```
node_modules/
#.env
package-lock.json
.vscode/
.idea
```

All working good

**Comment by wksantiago** [comment]
All working great thanks Michael and Tomislav
